git:
  depth: 3

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

    - os: osx
      osx_image: xcode7.3
      sudo: required

addons:
  apt:
    packages:
      - flex
      - bison

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install flex bison; fi
  - sudo sh ./scripts/install_gtest.sh

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
